// Array de dicas:
window.dicas = [
  "Leia atentamente o enunciado: no Cebraspe, qualquer detalhe pode inverter o sentido da questão.",
  "Questões do tipo CERTO ou ERRADO: uma resposta errada anula uma certa, atenção ao chute.",
  "Evite chutar em excesso: cada erro vale -1 ponto, então só marque se tiver convicção.",
  "Respeite o tempo da prova: calcule quantos minutos pode gastar em cada questão.",
  "Se travar em uma questão, pule e volte depois. Não perca tempo precioso.",
  "Treine bastante leitura rápida e interpretação de textos longos.",
  "Questões do Cebraspe são conhecidas por pegadinhas sutis em palavras como 'apenas', 'sempre', 'nunca'.",
  "Não confunda 'pode' com 'deve': isso muda completamente o sentido da afirmativa.",
  "Revise as matérias com base em provas anteriores do mesmo órgão.",
  "A banca costuma cobrar interpretação mais do que decoreba.",
  "Marque com calma: um erro pode destruir um acerto anterior.",
  "Tenha atenção redobrada em enunciados negativos: 'NÃO é correto afirmar que...'.",
  "Faça provas anteriores cronometrado, simulando as condições reais.",
  "Estude as legislações específicas atualizadas, Cebraspe cobra texto de lei seco.",
  "Controle sua ansiedade durante a prova, respire fundo e mantenha o foco.",
  "Revise mais vezes as disciplinas com maior peso no edital.",
  "Treine o uso de marca-texto para destacar palavras-chave no enunciado.",
  "Evite pular instruções: muitos erram por ignorar observações da banca.",
  "Sempre confira o gabarito oficial depois, para entender os padrões da banca.",
  "Lembre-se: Cebraspe gosta de 'pegadinhas semânticas', foque nos termos exatos.",
  "Na semana da prova, priorize revisão e resolução de questões, não novo conteúdo.",
  "Durante a leitura, sublinhe termos como: apenas, sempre, somente, nunca, necessariamente.",
  "Mantenha regularidade nos estudos: Cebraspe cobra interdisciplinaridade.",
  "Administre o tempo de redação (quando houver), ela tem peso grande em concursos.",
  "Evite mudar resposta sem motivo forte: a primeira escolha costuma estar certa.",
  "Aprenda a identificar padrões: Cebraspe costuma repetir estilo de perguntas.",
  "Use a técnica de eliminação: se não tem certeza, elimine o que está claramente errado.",
  "Domine interpretação de gráficos, tabelas e esquemas, caem bastante.",
  "Organize-se para não deixar questões em branco, exceto quando o chute for arriscado.",
  "Revise os erros cometidos em simulados: são eles que mostram suas fraquezas.",
  "Leia o edital com atenção: o Cebraspe cobra exatamente o que está escrito.",
  "Não dependa só de resumos prontos, faça seus próprios materiais de revisão.",
  "Treine a leitura e interpretação de leis e normas jurídicas.",
  "Mantenha atenção às atualidades, Cebraspe gosta de cobrar contexto.",
  "Aprenda a lidar com o psicológico: prova Cebraspe exige estratégia e sangue frio."
];
